IceCream/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace IceCream.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }
        [ForeignKey("ApplicationUser")]
        public string OwnerId { get; set; }
        public virtual ApplicationUser ApplicationUser { get; set; }
        public double TotalPrice { get; set; }
        public string ShipName { get; set; }       
        public string ShipAddress { get; set; }
        public string ShipPhone { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }        
        public int Status { get; set; }       
    }
}

IceCream/Controllers/CartController.cs
using IceCream.Models;
using IceCream.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IceCream.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Cart
        /*[Authorize]*/
        public ActionResult Index()
        {
            List<CartItem> cartItems = new List<CartItem>();
            var cartModel = new CartModel();
            if(cartModel.GetCartItems() != null)
            {
                cartItems = cartModel.GetCartItems();
            }
            ViewBag.Tax = cartModel.TaxMoney();
            ViewBag.GrandTotal = cartModel.GrandTotalMoney();
            ViewBag.SubTotal = cartModel.CalcTotalMoney();
            return View(cartItems);
        }
        [Authorize]
        public ActionResult AddToCart(int id)
        {
            var product = db.Books.Find(id);
            var cartModel = new CartModel();
            if(product == null)
            {
                return RedirectToAction("Product", "Home");
            }
            var cartItem = new CartItem()
            {
                Id = product.Id,
                ProductName = product.Title,
                Price = product.Price,
                Quantity = 1,
                Thumbnail = product.Thumbnail
            };
            cartModel.AddItem(cartItem);
            return RedirectToAction("Index");
        }

        public ActionResult RemoveCartItem(int id)
        {
            var cartModel = new CartModel();
            cartModel.RemoveItem(id);
            return RedirectToAction("Index");
        }


        [HttpPost]
        public ActionResult UpdateCart(UpdateCartItem updateCartItem)
        {
            var cartModel = new CartModel();
            cartModel.UpdateItem(updateCartItem.Id, updateCartItem.Quantity);
            var tax = cartModel.TaxMoney();
            var grandTotal = cartModel.GrandTotalMoney();
            var subTotal = cartModel.CalcTotalMoney();
            return Json(new
            {
                subTotal = subTotal,
                tax = tax,
                grandTotal = grandTotal
            });
        }      
        
        public ActionResult Payment()
        {
            List<CartItem> cartItems = new List<CartItem>();
            var cartModel = new CartModel();
            if (cartModel.GetCartItems() != null)
            {
                cartItems = cartModel.GetCartItems();
            }
            ViewBag.Tax = cartModel.TaxMoney();
            ViewBag.GrandTotal = cartModel.GrandTotalMoney();
            ViewBag.SubTotal = cartModel.CalcTotalMoney();
            return View(cartItems);
        }
    }
}

IceCream/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IceCream.Models;
using Microsoft.AspNet.Identity;

namespace IceCream.Controllers
{
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        // GET: Orders
        public ActionResult Index()
        {
            var orderId = Session["OrderId"];
            if(orderId == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var order = db.Orders.Find(orderId);
            if(order.Status == 4)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            ViewBag.OwnerId = new SelectList(db.Users, "Id", "FullName");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,OwnerId,ShipName,ShipAddress,ShipPhone")] Order order)
        {           
            var cart = new CartModel();          
            if (ModelState.IsValid)
            {
                order.OwnerId = User.Identity.GetUserId();
                order.TotalPrice = cart.GrandTotalMoney();
                order.CreatedAt = DateTime.Now;
                order.UpdatedAt = DateTime.Now;
                order.Status = 1;
                db.Orders.Add(order);
                foreach(var cartItem in cart.GetCartItems())
                {
                    var orderDetails = new OrderDetail()
                    {
                        BookId = cartItem.Id,
                        BookName = cartItem.ProductName,
                        BookThumbnail = cartItem.Thumbnail,
                        Quantity = cartItem.Quantity,
                        UnitPrice = cartItem.Price,
                        OrderId = order.Id,
                    };
                    db.OrderDetails.Add(orderDetails);
                }
                db.SaveChanges();
                Session["GrandTotal"] = cart.GrandTotalMoney();
                Session["OrderId"] = order.Id;
                cart.RemoveCartModel();
                return RedirectToAction("Index");
            }
            ViewBag.OwnerId = new SelectList(db.Users, "Id", "FullName", order.OwnerId);           
            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.OwnerId = new SelectList(db.Users, "Id", "FullName", order.OwnerId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,OwnerId,TotalPrice,ShipName,ShipAddress,ShipPhone,CreatedAt,UpdatedAt,Status")] Order order)
        {            
            if (ModelState.IsValid)
            {         
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.OwnerId = new SelectList(db.Users, "Id", "FullName", order.OwnerId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        public ActionResult PaymentOrder(int id)
        {
            var order = db.Orders.Find(id);
            if(order != null)
            {
                order.Status = 4;
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
            }
            return Json(new { 
                message = "Payment successfull",
            });
        }
    }
}

IceCream/Views/Orders/Create.cshtml
@model IceCream.Models.Order

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="col-md-6">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.ShipName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipPhone, "", new { @class = "text-danger" })
            </div>
        </div>
      
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Cart", "Index","Cart")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IceCream/Views/Orders/Delete.cshtml
@model IceCream.Models.Order

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IceCream/Views/Orders/Details.cshtml
@model IceCream.Models.Order

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IceCream/Views/Orders/Edit.cshtml
@model IceCream.Models.Order

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerId, "OwnerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OwnerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OwnerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IceCream/Views/Orders/Index.cshtml
@section scripts{
    <script>
        $(function () {
            $('#AlertBox').removeClass('hide');
            $('#AlertBox').delay(2000).slideUp(500);
        });

    </script>
    <style>
        #AlertBox {
            width: 450px;
            height: auto;
            margin: 20px 50px 50px 450px
        }
    </style>
    <script src="https://www.paypal.com/sdk/js?client-id=ATaO6gSwSEFH529YajeVFV36WXXX-KeTvWA3ycyLsFnwF6P8LPTX6ZxV_s7DSNbvb4HFiLpIlktX_DzM&components=buttons"></script>
    <script>
        paypal.Buttons({
            createOrder: function (data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: "@HttpContext.Current.Session["GrandTotal"]"
                        }
                    }]
                });
            },
            onApprove: function (data, actions) {
                return actions.order.capture().then(function (details) {
                    $.ajax({
                            url: '@Url.Action("PaymentOrder", "Orders", new { @id = HttpContext.Current.Session["OrderId"] })',
                            dataType: "json",
                            type: "POST",
                            contentType: 'application/json; charset=utf-8',
                            data: JSON.stringify({
                                id: @HttpContext.Current.Session["OrderId"]
                            }),
                            success: function (data) {
                                console.log(data);
                                $('#paypal-button-container').hide();
                                $('#AlertBox').show();
                                $('#AlertBox').html("You have successfully paid");
                            },
                            error: function (xhr) {
                            },
                        });
                });
            }
        }).render('#paypal-button-container');
    </script>
}
<div class="alert alert-success" id="AlertBox" role="alert">
    Your order has been successfully placed!
</div>
<div id="paypal-button-container" class="d-flex justify-content-center">

</div>