IceCream/Controllers/CartController.cs
using IceCream.Models;
using IceCream.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IceCream.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Cart
        /*[Authorize]*/
        public ActionResult Index()
        {
            List<CartItem> cartItems = new List<CartItem>();
            var cartModel = new CartModel();
            if(cartModel.GetCartItems() != null)
            {
                cartItems = cartModel.GetCartItems();
            }
            ViewBag.Tax = cartModel.TaxMoney();
            ViewBag.GrandTotal = cartModel.GrandTotalMoney();
            ViewBag.SubTotal = cartModel.CalcTotalMoney();
            return View(cartItems);
        }
        [Authorize]
        public ActionResult AddToCart(int id)
        {
            var product = db.Books.Find(id);
            var cartModel = new CartModel();
            if(product == null)
            {
                return RedirectToAction("Product", "Home");
            }
            var cartItem = new CartItem()
            {
                Id = product.Id,
                ProductName = product.Title,
                Price = product.Price,
                Quantity = 1,
                Thumbnail = product.Thumbnail
            };
            cartModel.AddItem(cartItem);
            return RedirectToAction("Index");
        }

        public ActionResult RemoveCartItem(int id)
        {
            var cartModel = new CartModel();
            cartModel.RemoveItem(id);
            return RedirectToAction("Index");
        }


        [HttpPost]
        public ActionResult UpdateCart(UpdateCartItem updateCartItem)
        {
            var cartModel = new CartModel();
            cartModel.UpdateItem(updateCartItem.Id, updateCartItem.Quantity);
            var tax = cartModel.TaxMoney();
            var grandTotal = cartModel.GrandTotalMoney();
            var subTotal = cartModel.CalcTotalMoney();
            return Json(new
            {
                subTotal = subTotal,
                tax = tax,
                grandTotal = grandTotal
            });
        }      
        
        public ActionResult Payment()
        {
            List<CartItem> cartItems = new List<CartItem>();
            var cartModel = new CartModel();
            if (cartModel.GetCartItems() != null)
            {
                cartItems = cartModel.GetCartItems();
            }
            ViewBag.Tax = cartModel.TaxMoney();
            ViewBag.GrandTotal = cartModel.GrandTotalMoney();
            ViewBag.SubTotal = cartModel.CalcTotalMoney();
            return View(cartItems);
        }
    }
}

IceCream/Controllers/RecipeClientController.cs
using IceCream.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IceCream.Controllers
{
    public class RecipeClientController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        // GET: RecipeClient
        public ActionResult Index()
        {          
            return View();          
        }
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FullName");
            return View();
        }

        // POST: Admin/Recipes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,AuthorId,Name,Description,Thumbnail,Materral,DetailStep")] Recipe recipe)
        {
            if (ModelState.IsValid)
            {
                recipe.AuthorId = User.Identity.GetUserId();
                recipe.CreatedAt = DateTime.Now;
                recipe.UpdatedAt = DateTime.Now;
                recipe.Status = 1;
                db.Recipes.Add(recipe);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FullName", recipe.AuthorId);
            return View(recipe);
        }
    }
}

IceCream/Views/Shared/_Footer.cshtml
 <!-- Footer Start -->
<div class="container-fluid footer bg-light py-5" style="margin-top: 90px;">
    <div class="container text-center py-5">
        <div class="row">
            <div class="col-12 mb-4">
                <a href="index.html" class="navbar-brand m-0">
                    <h1 class="m-0 mt-n2 display-4 text-primary"><span class="text-secondary">ICE</span>CREAM</h1>
                </a>
            </div>
            <div class="col-12 mb-4">
                <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-twitter"></i></a>
                <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                <a class="btn btn-outline-secondary btn-social" href="#"><i class="fab fa-instagram"></i></a>
            </div>
            <div class="col-12 mt-2 mb-4">
                <div class="row">
                    <div class="col-sm-6 text-center text-sm-right border-right mb-3 mb-sm-0">
                        <h5 class="font-weight-bold mb-2">Get In Touch</h5>
                        <p class="mb-2">8 Ton That Thuyet, Mi Dinh 2, Cau Giay, Ha Noi</p>
                        <p class="mb-0">096 461 5565 - 098 197 7600 (24/7)</p>
                        <p class="mb-0">ICream@gmail.com</p>
                    </div>
                    <div class="col-sm-6 text-center text-sm-left">
                        <h5 class="font-weight-bold mb-2">Commit</h5>                        
                        <p class="mb-2"> Rich and diverse products</p>
                        <p class="mb-0">Fast delivery, on time</p>
                        <p class="mb-0">Always good prices, many promotions </p>                                   
                    </div>
                </div>
            </div>
            <div class="col-12">
                <p class="m-0">
                    &copy; <a href="#">Domain</a>. 1990-2022 ICE Cream reserves all rights</a>
                </p>
            </div>
        </div>
    </div>
</div>

IceCream/Views/Shared/_Navbar.cshtml
   <!-- Topbar Start -->
@using Microsoft.AspNet.Identity
@using IceCream.Models;
@{
    ApplicationDbContext db = new ApplicationDbContext();
    var userid = User.Identity.GetUserId();
    var user = db.Users.Where(x => x.Id == userid).FirstOrDefault();
    if (user != null)
    {
        ViewBag.Avatar = user.Avatar;
    }


}

<div class="container-fluid bg-primary py-3 d-none d-md-block">
    <div class="container">
        <div class="row">
            <div class="col-md-6 text-center text-lg-left mb-2 mb-lg-0">
                <div class="d-inline-flex align-items-center">
                    <a class="text-white pr-3" href="">FAQs</a>
                    <a class="text-white pr-3" href="">Help</a>
                    <a class="text-white" href="">Support</a>

                    @if (Request.IsAuthenticated)
                    {
                        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="dropdown">
                                <a class="ml-3 d-flex align-items-center text-black-50 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <div class="avatar">
                                        <img src="@ViewBag.Avatar" alt="@User.Identity.GetUserName()" />
                                    </div>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="javascript:document.getElementById('logoutForm').submit()">Log off</a>
                                    @Html.ActionLink("Profile", "Profile", "Home", routeValues: null, htmlAttributes: new { @class = "dropdown-item" })
                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        @Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink", @class = "ml-3 text-white" })
                        @Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "ml-3 text-white" })
                    }
                    <a class="text-white pl-3" href="@Url.Action("Index", "Cart")">
                        <i class="fa fa-shopping-cart">
                            @{
                                var cart = HttpContext.Current.Session["cartModel"] as List<IceCream.Models.CartItem>;
                            }
                            @if (cart != null)
                            {
                                <b>@cart.Count</b>

                            }
                        </i>                      
                    </a>
                </div>
            </div>
            <div class="col-md-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-white px-3" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-white px-3" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-white px-3" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-white px-3" href="">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-white pl-3" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Topbar End -->
<!-- Navbar Start -->
<div class="container-fluid position-relative nav-bar p-0">
    <div class="container-lg position-relative p-0 px-lg-3" style="z-index: 9;">
        <nav class="navbar navbar-expand-lg bg-white navbar-light shadow p-lg-0">
            <a href="index.html" class="navbar-brand d-block d-lg-none">
                <h1 class="m-0 display-4 text-primary"><span class="text-secondary">ICE</span>CREAM</h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                <div class="navbar-nav ml-auto py-0">
                    <a href="@Url.Action("Index", "Home")" class="nav-item nav-link">
                        Home
                    </a>
                    <div class="dropdown">
                        <a class="ml-3 d-flex align-items-center  dropdown-toggle nav-item nav-link" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Recipe
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            @Html.ActionLink("Recipe", "Recipe", "Home", routeValues: null, htmlAttributes: new { @class = " dropdown-item" })                    
                            @Html.ActionLink("Share Recipe", "Create", "RecipeClient", routeValues: null, htmlAttributes: new { @class = " dropdown-item" })                    
                        </div>
                    </div>           
                    <a href="@Url.Action("Product", "Home")" class="nav-item nav-link">
                        Book
                    </a>
                </div>
                <a href="/" class="navbar-brand mx-5 d-none d-lg-block">
                    <h1 class="m-0 display-4 text-primary"><span class="text-secondary">ICE</span>CREAM</h1>
                </a>
                <div class="navbar-nav mr-auto py-0">
                    @Html.ActionLink("About", "About", "Home", new { @class = "nav-item nav-link" })
                    <a href="award.html" class="nav-item nav-link">Awards</a>
                    @Html.ActionLink("Contact", "Contact", "Home", new { @class = "nav-item nav-link" })
                </div>
            </div>
        </nav>
    </div>
</div>
<!-- Navbar End -->