IceCream/Areas/Admin/Controllers/AdminOrdersController.cs
using IceCream.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace IceCream.Areas.Admin.Controllers
{   
    public class AdminOrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        // GET: Admin/AdminOrders
        public ActionResult Index()
        {
            User.Identity.GetUserId();
            var orders = db.Orders.OrderByDescending(o => o.CreatedAt).ToList();
            return View(orders);
        }
        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.OwnerId = new SelectList(db.Users, "Id", "FullName", order.OwnerId);
            var orderDetails = db.OrderDetails.Where(oD => oD.OrderId == order.Id).ToList();
            ViewBag.OrderDetails = orderDetails;
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,OwnerId,TotalPrice,ShipName,ShipAddress,ShipPhone,CreatedAt,UpdatedAt,Status")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.OwnerId = new SelectList(db.Users, "Id", "FullName", order.OwnerId);
            return View(order);
        }
    }
}

IceCream/Areas/Admin/Views/AdminOrders/Delete.cshtml
@model IceCream.Models.Order

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IceCream/Areas/Admin/Views/AdminOrders/Edit.cshtml
@model IceCream.Models.Order
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerId, "OwnerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OwnerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OwnerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


@{
    var orderDetails = ViewBag.OrderDetails as List<IceCream.Models.OrderDetail>;
}

<table class="table stripe  nowrap">
    <thead>
        <tr>
            <th>Id</th>
            <th>Thumbnail</th>
            <th>Product Name</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var orderItem in orderDetails)
        {
            <tr>
                <td>
                    @orderItem.Id
                </td>
                <td>
                    <img width="200" src=" @orderItem.BookThumbnail" />
                </td>
                <td> @orderItem.BookName</td>
                <td> @orderItem.Quantity</td>
                <td> @orderItem.UnitPrice</td>
                <td>
                    @{
                        var total = orderItem.Quantity * orderItem.UnitPrice;
                    }
                    @total
                </td>
            </tr>
        }

    </tbody>
</table>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IceCream/Areas/Admin/Views/AdminOrders/Index.cshtml
@model IEnumerable<IceCream.Models.Order>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<head>
    <!-- Basic Page Info -->
    <meta charset="utf-8">
    <title>DeskApp - Bootstrap Admin Dashboard HTML Template</title>

    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/Areas/Admin/ContentAdmin/vendors/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Areas/Admin/ContentAdmin/vendors/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Areas/Admin/ContentAdmin/vendors/images/favicon-16x16.png">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/ContentAdmin/vendors/styles/core.css">
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/ContentAdmin/vendors/styles/icon-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/ContentAdmin/src/plugins/datatables/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/ContentAdmin/src/plugins/datatables/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/ContentAdmin/vendors/styles/style.css">


</head>
<body>
    <table class="data-table table stripe hover nowrap" >
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ApplicationUser.FullName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ShipName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ShipAddress)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ShipPhone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UpdatedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th></th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationUser.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ShipName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ShipAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ShipPhone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdatedAt)
                </td>
                <td>
                    @if (item.Status == 1)
                    {
                        <a class="text-warning">
                            Pending
                        </a>
                    }
                    else if (item.Status == 2)
                    {
                        <a class="text-primary">
                            Shipping
                        </a>
                    }
                    else if (item.Status == 3)
                    {
                        <a class="text-success">
                            Done
                        </a>
                    }
                    else if (item.Status == 4)
                    {
                        <a class="text-success">
                    Paid
                        </a>
                    }

                </td>
                <td>
                    <div class="d-flex">
                        <a class="m-2" href="@Url.Action("Edit","AdminOrders", new { @item.Id})">
                            <h5><i class="dw dw-edit2 btn btn-primary"></i></h5>
                        </a>
                        <a class="m-2" href="@Url.Action("Delete","AdminOrders", new { @item.Id})">
                            <h5><i class="dw dw-delete-3 btn btn-danger"></i></h5>
                        </a>
                    </div>
                </td>
            </tr>
        }

    </table>

    <!-- js -->
    <script src="~/Areas/Admin/ContentAdmin/vendors/scripts/core.js"></script>
    <script src="~/Areas/Admin/ContentAdmin/vendors/scripts/script.min.js"></script>
    <script src="~/Areas/Admin/ContentAdmin/vendors/scripts/process.js"></script>
    <script src="~/Areas/Admin/ContentAdmin/vendors/scripts/layout-settings.js"></script>
    <script src="~/Areas/Admin/ContentAdmin/src/plugins/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/Areas/Admin/ContentAdmin/src/plugins/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Areas/Admin/ContentAdmin/src/plugins/datatables/js/dataTables.responsive.min.js"></script>
    <script src="src/plugins/datatables/js/responsive.bootstrap4.min.js"></script>
    <!-- buttons for Export datatable -->
    <script src="~/Areas/Admin/ContentAdmin/src/plugins/datatables/js/dataTables.buttons.min.js"></script>
    <script src="~/Areas/Admin/ContentAdmin/src/plugins/datatables/js/buttons.bootstrap4.min.js"></script>
    <script src="~/Areas/Admin/ContentAdmin/src/plugins/datatables/js/buttons.print.min.js"></script>
    <script src="~/Areas/Admin/ContentAdmin/src/plugins/datatables/js/buttons.html5.min.js"></script>
    <script src="~/Areas/Admin/ContentAdmin/src/plugins/datatables/js/buttons.flash.min.js"></script>
    <script src="~/Areas/Admin/ContentAdmin/src/plugins/datatables/js/pdfmake.min.js"></script>
    <script src="~/Areas/Admin/ContentAdmin/src/plugins/datatables/js/vfs_fonts.js"></script>
    <!-- Datatable Setting js -->
    <script src="~/Areas/Admin/ContentAdmin/vendors/scripts/datatable-setting.js"></script>
</body>